#!/bin/bash

# Get directory paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

# Check if output.asm exists in the parent directory
if [ -f "$PARENT_DIR/output.asm" ]; then
    echo "Found output.asm at $PARENT_DIR/output.asm"
else
    echo "Creating sample output.asm file"
    cat > "$PARENT_DIR/output.asm" << 'EOL'
// pPIM Assembly generated by pPIM Compiler
// Format: <Instruction> <Parameters>

PROG Core0 MULTIPLIER [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07]
PROG Core1 ADDER [0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f]
PROG Core2 MAC [0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17]
EXE Read RowAddress0
EXE Read RowAddress1
EXE CorePtr0 RowAddress0
EXE Read RowAddress0
EXE Read RowAddress1
EXE CorePtr2 RowAddress0
EXE Write RowAddress2
END
EOL
    echo "Sample output.asm created"
fi

# Create necessary directories for visualization outputs
mkdir -p "$SCRIPT_DIR/temp_images"

# Ensure required Python packages are installed
echo "Checking Python packages..."
pip install -q streamlit numpy pandas matplotlib pillow

echo "Setup complete! Run ./run_visualization.sh to start the visualization." 